// -- Service Actions -- //
export const SERVICE_ERROR = 'SERVICE_ERROR';

// -- Auth / Session -- //
export const AUTHORIZE_REQUEST = 'AUTHORIZE_REQUEST';

export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_ERROR = 'LOG_IN_ERROR';
export const LOG_IN_CHECK = 'LOG_IN_CHECK';

export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';

export const SESSION_EXPIRED = 'SESSION_EXPIRED';

// -- Account -- //
export const ACCOUNT_ME_GET_REQUEST = 'ACCOUNT_ME_GET_REQUEST';
export const ACCOUNT_ME_GET_SUCCESS = 'ACCOUNT_ME_GET_SUCCESS';
export const ACCOUNT_ME_GET_ERROR = 'ACCOUNT_ME_GET_ERROR';
export const ACCOUNT_ME_CHECK = 'ACCOUNT_ME_CHECK';

// -- Artists Following -- //
export const ARTISTS_FOLLOWING_GET_REQUEST = 'ARTISTS_FOLLOWING_GET_REQUEST';
export const ARTISTS_FOLLOWING_GET_SUCCESS = 'ARTISTS_FOLLOWING_GET_SUCCESS';
export const ARTISTS_FOLLOWING_GET_ERROR = 'ARTISTS_FOLLOWING_GET_ERROR';

export const ARTISTS_FOLLOWING_UPDATE_REQUEST = 'ARTISTS_FOLLOWING_UPDATE_REQUEST';
export const ARTISTS_FOLLOWING_UPDATE_SUCCESS = 'ARTISTS_FOLLOWING_UPDATE_SUCCESS';
export const ARTISTS_FOLLOWING_UPDATE_ERROR = 'ARTISTS_FOLLOWING_UPDATE_ERROR';

export const ARTISTS_FOLLOWING_DELETE_REQUEST = 'ARTISTS_FOLLOWING_DELETE_REQUEST';
export const ARTISTS_FOLLOWING_DELETE_SUCCESS = 'ARTISTS_FOLLOWING_DELETE_SUCCESS';
export const ARTISTS_FOLLOWING_DELETE_ERROR = 'ARTISTS_FOLLOWING_DELETE_ERROR';

// -- Artists Related -- //
export const ARTISTS_RELATED_GET_REQUEST = 'ARTISTS_RELATED_GET_REQUEST';
export const ARTISTS_RELATED_GET_SUCCESS = 'ARTISTS_RELATED_GET_SUCCESS';
export const ARTISTS_RELATED_GET_ERROR = 'ARTISTS_RELATED_GET_ERROR';

export const ARTISTS_RELATED_RESET = 'ARTISTS_RELATED_RESET';


